### ISSUE TITLE
[BUG]: Permission denied when executing docker-entrypoint.sh

### ISSUE THREAD

**Issue by dest1n1s** [ImBIOS/bun-node#10] opened 2024-01-08 03:01 UTC
### Description of the bug

I'm taking advantaged of `imbios/bun-node:latest` to containerized my Next.js app using the Dockerfile from the [example](https://github.com/ImBIOS/bun-node/blob/main/examples/next/default-app-dir/dockerfile). 

When I try to run the built container, it gets into error with following messages:

```plaintext
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/docker-entrypoint.sh": permission denied: unknown
```

This problem is also observed by directly building and running the [Next.js app example](https://github.com/ImBIOS/bun-node/blob/main/examples/next/default-app-dir).

I think there's some problems with the permission of `/usr/local/bin/docker-entrypoint.sh` in the container. By simply adding 

```docker
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
```

to the Dockerfile, the problem gets fixed.

Besides, there's a typo in the 8th line of the example Dockerfile, where `bun.lockb` is mistyped as `bun.lock`.

### Environment

```plaintext
  System:
    OS: Linux 6.6 Arch Linux
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600K
    Memory: 13.50 GB / 31.09 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 21.5.0 - /usr/bin/node
    npm: 10.2.5 - /usr/bin/npm
    pnpm: 8.14.0 - /usr/bin/pnpm
    bun: 1.0.21 - /usr/bin/bun
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
    Java: 1.8.0_392 - /usr/bin/javac
    Perl: 5.38.1 - /usr/bin/perl
    Protoc: 25.1 - /usr/bin/protoc
    Python: 3.11.6 - /usr/bin/python
    Python3: 3.11.6 - /usr/bin/python3
```

### Steps To Reproduce

1. Clone the repository;
2. Run `cd examples/next/default-app-dir`;
3. Run `docker buildx build . -t next-app-example` to build the image;
4. Run `docker run next-app-example` to run the container.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ImBIOS** [comment] 2024-01-08 04:18
@dest1n1s thanks for mentioning potential solution for this issue, would you like to open a PR regarding this issue?

**Comment by colinricardo** [comment] 2024-01-08 16:42
having this issue too

**Comment by ImBIOS** [comment] 2024-01-09 01:03
okay, let me handle it. for the moment, if it's in production, you can roll back to any image version available that works for your project.

**Comment by jjrise** [comment] 2024-01-29 19:36
looks like you pushed a fix but I'm still getting the same permission denied on :latest ?

```
FROM imbios/bun-node:latest

# this fixes it....
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

```

**Comment by Marknjo** [comment] 2024-02-02 14:23
@jjrise thanks for that tip. However, I suppose everyone reading this will wonder where exactly to add this line. If you are in that boat, here is an example in a NextJs setup with two stages - dev & production. 

```yaml 

FROM imbios/bun-node:latest As development 

WORKDIR /usr/src/app


COPY package.json ./
COPY bun.lockb ./

RUN bun install

COPY . .

RUN bun run build
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
```
Kindly note the command is right after the build command (this important in my case)

**Comment by ImBIOS** [comment] 2024-02-06 02:16
- https://github.com/ImBIOS/bun-node/commit/c0d320163e581c286e200ea0d4361ab233164618#commitcomment-138277217

@dest1n1s @Marknjo @colinricardo @jjrise found out that I forgot to build each of the latest updates, are these problems been solved on your side?

**Comment by Marknjo** [comment] 2024-02-15 05:13
@ImBIOS Tested today and the problem is gone. Thanks 😃

**Comment by jjrise** [comment] 2024-02-15 23:20
works for me too! Thanks!

**Comment by scippio** [comment] 2024-03-07 12:43
Same error with imbios/bun-node:1-20.10-alpine

**Comment by ImBIOS** [comment] 2024-03-09 06:11
@scippio Sorry, it might take more time than I expected, I can't even reproduce. I'm facing this issue with Docker at the moment: 
- https://github.com/docker/for-win/issues/13960

I appreciate it if anyone wants to help.

**Comment by scippio** [comment] 2024-03-10 09:51
Oh, I'm sorry I don't using any Windows things.

**Comment by ImBIOS** [comment] 2024-03-13 03:01
@scippio I can't reproduce the issue, I consider this as another issue. Please open a new issue with some details so I can reproduce and help you fix this issue.

```
󰀵  󱑍 09:57  ﱮ bun-node    main  via 🐍 v3.10.12 
 ✗  docker run --expose 3000 next-app-example     
$ next start
   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000

 ✓ Ready in 462ms
```

**Comment by ImBIOS** [comment] 2024-03-14 04:26
@scippio Fixed here:
- https://github.com/ImBIOS/bun-node/actions/runs/8275443115

I forgot to rebuild all images which have permission issues. I'm considering rebuilding all of it after pin point exactly every images which need this.

**Closed** 2024-03-14 04:42 UTC
Labels: bug
